#!/usr/bin/env ruby

# pre-commit hook for Rails app to look for bad strings that shouldn't be checked in
# Copyright (c) 2009 Andy Atkinson
bad_strings = %w(debugger console)
raw_results = ''
bad_strings.each{|s| raw_results += `find * -exec grep -l '#{s}' {} \\;`}
results = raw_results.split.reject{|w| w.match(/vendor|log|script\//)} # ignore certain rails dirs
results = results.reject{|r| r.match(/jquery-ui.js|jquery.form.js/)} # CUSTOMIZE - ignore certain files
if results.size > 0
  puts "PRE-COMMIT ERROR\nOne or more bad strings:\n#{bad_strings.join(' ')}\n \
  ...found in the following files:\n#{results.join(' ')}\n\nREQUIRED: Remove bad strings before committing."
  exit 1
else
  exit 0
end